/**
 *                            *** MIT LICENSE ***
 * -------------------------------------------------------------------------
 * This code may be modified and distributed under the MIT license.
 * See the LICENSE file for details.
 * -------------------------------------------------------------------------
 *
 * @summary   A hello world example for the landing page.
 *
 * @author    Alvis HT Tang <alvis@hilbert.space>
 * @license   MIT
 * @copyright Copyright (c) 2018 - All Rights Reserved.
 * -------------------------------------------------------------------------
 */

import { graphql } from 'gatsby';
import React, { PureComponent } from 'react';
import Helmet from 'react-helmet';

import Layout from '#layouts/Landing';

import { IndexQuery } from '#definitions/gatsby';
import { PageProps } from '#definitions/gatsby/page';

// page query
export const query = graphql`
  query IndexQuery {
    site {
      siteMetadata {
        title
      }
    }
  }
`;

/** the main landing page */
export default class Index extends PureComponent<PageProps<IndexQuery>> {
  /** @inheritdoc */
  public displayName: string = 'Layout';

  /** @inheritdoc */
  public render(): JSX.Element {
    const data = this.props.data;
    const title =
      data &&
      data.site &&
      data.site.siteMetadata &&
      data.site.siteMetadata.title;

    return (
      <>
        <Helmet title="Gatsby with Typescript" />
        <Layout>
          {title ? <h1>{title}</h1> : null}
          <p>A site generated by Gatsby</p>
        </Layout>
      </>
    );
  }
}
